user = User.create!(name: 'naresh', email: 'naresh@gmail.com', password: '123456')
user2 = User.create!(name: 'gladston', email: 'gladston@gmail.com', password: '123456')
user.groups.create(name: 'group1', created_by: user)
user.groups.create(name: 'group2', created_by: user)
user2.user_groups.create(group: Group.first)
user.books.create(title: 'Theory of Everything')
user.books.create(title: 'Art of War')
user2.books.create(title: 'Harry Potter')
user2.user_books.create(book: Book.second)
